### ISSUE TITLE
Unsupported node relu

### ISSUE THREAD

**Issue by Mojtaba1515** [eml-eda/plinio#8]
![Screenshot 2023-05-29 141606](https://github.com/eml-eda/plinio/assets/134892413/863a0bd2-034f-41be-9bbe-7cda23eac131)
I tried relu, sigmoid and Tanh but still I get the ValueError of unsupported node relu... is it possible to modify the library codes to resolve my problem?

**Comment by matteorisso** [comment]
Dear @Mojtaba1515,
Please attach here the code of the network you are trying to use.

**Comment by Mojtaba1515** [comment]
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        
        self.conv1 = nn.Conv1d(in_channels=6, out_channels=10, kernel_size=3)
        self.bn1 = nn.BatchNorm1d(10)
        self.pool1 = nn.MaxPool1d(kernel_size=3, stride=3)
        
        self.conv2 = nn.Conv1d(in_channels=10, out_channels=44, kernel_size=3)
        self.dropout = nn.Dropout(p=0.5)
        
        self.conv3 = nn.Conv1d(in_channels=44, out_channels=35, kernel_size=3)
        self.pool2 = nn.MaxPool1d(kernel_size=3, stride=3)
        self.pool3 = nn.MaxPool1d(kernel_size=2, stride=2)
        
        self.bn2 = nn.BatchNorm1d(35)
        self.flatten = nn.Flatten()
        
        self.bn3 = nn.BatchNorm1d(140)
        self.bn4 = nn.BatchNorm1d(140)
        
        self.fc1 = nn.Linear(140, 60)
        self.fc2 = nn.Linear(60, 1)
        
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = torch.relu(x)
        x = self.pool1(x)
        
        x = self.conv2(x)
        x = self.dropout(x)
        x = torch.relu(x)
        
        x = self.conv3(x)
        x = self.pool2(x)
        x = self.pool3(x)
        x = self.bn2(x)
        x = torch.relu(x)
        
        x = self.flatten(x)
        
        x = self.bn3(x)
        x = torch.relu(x)
        
        x = self.bn4(x)
        x = torch.relu(x)
        
        x = self.fc1(x)
        x = torch.relu(x)
        
        x = self.fc2(x)
        
        return x

# Create an instance of the model
model = MyModel()
model= PIT(model, input_shape=(6,100))

**Comment by matteorisso** [comment]
Dear @Mojtaba1515, with the latest commit 492e20c I added support for all the activation functions you requested.

**Comment by Mojtaba1515** [comment]
Dear Matteo

Thank you so much for adding those activation functions. When I run above code I get following error "ValueError: Unsupported node flatten (op: call_module, target: flatten)". I appreciate if you are able to add flatten to resolve my issue. Thank you for your time!

**Comment by matteorisso** [comment]
Latest commit [a689985](https://github.com/eml-eda/plinio/commit/a689985bd77d87bc209d59687ae1914691e26921) add support for the nn.Flatten modules.

**Comment by Mojtaba1515** [comment]
Dear Matteo,

I could compile my model successfully. When I run the model I receive an error in the training loop as follow: AttributeError: 'PITBatchNorm1d' object has no attribute 'out_features_eff' 
This error is related to this line of code in the training loop: loss=task_loss+model.get_regularization_loss()
How can I resolve this issue?
I will paste my model architecture and training loop for your review:

import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        
        self.conv1 = nn.Conv1d(in_channels=6, out_channels=10, kernel_size=3)
        self.bn1 = nn.BatchNorm1d(10)
        self.pool1 = nn.MaxPool1d(kernel_size=3, stride=3)
        
        self.conv2 = nn.Conv1d(in_channels=10, out_channels=44, kernel_size=3)
        self.dropout = nn.Dropout(p=0.5)
        
        self.conv3 = nn.Conv1d(in_channels=44, out_channels=35, kernel_size=3)
        self.pool2 = nn.MaxPool1d(kernel_size=3, stride=3)
        self.pool3 = nn.MaxPool1d(kernel_size=2, stride=2)
        
        self.bn2 = nn.BatchNorm1d(35)
        self.flatten =  nn.Flatten()
        
        self.bn3 = nn.BatchNorm1d(140)
        self.bn4 = nn.BatchNorm1d(140)
        
        self.fc1 = nn.Linear(140, 60)
        self.fc2 = nn.Linear(60, 1)
        
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = torch.relu(x)
        x = self.pool1(x)
        
        x = self.conv2(x)
        x = self.dropout(x)
        x = torch.nn.functional.relu(x)
        
        x = self.conv3(x)
        x = self.pool2(x)
        x = self.pool3(x)
        x = self.bn2(x)
        x = torch.nn.functional.relu(x)
        
        x = self.flatten(x)
        
        x = self.bn3(x)
        x = torch.nn.functional.relu(x)
        
        x = self.bn4(x)
        x = torch.nn.functional.relu(x)
        
        x = self.fc1(x)
        x = torch.nn.functional.relu(x)
        
        x = self.fc2(x)
        
        return x

# Create an instance of the model
model = MyModel()
model= PIT(model, input_shape=(6,100))



##########################The codes related to training loop:
import torch
import torch.nn as nn
import torch.optim as optim
model = model.float()
# Define your training data and labels
train_data = torch.tensor(window_all_X).float() # Your training data
train_labels = torch.tensor(window_all_y).float() # Your training labels

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Set the model in training mode
model.train()
batch_size=500
# Define the number of training epochs
num_epochs = 10

# Training loop
for epoch in range(num_epochs):
    running_loss = 0.0
    
    # Iterate over the training data in batches
    for i in range(0, len(train_data), batch_size):
        # Extract the current batch
        inputs = train_data[i:i+batch_size]
        labels = train_labels[i:i+batch_size]
        
        # Clear the gradients
        optimizer.zero_grad()
        
        # Forward pass
        outputs = model(inputs)
        
        # Compute the loss
        task_loss = criterion(outputs, labels)
        loss=task_loss+model.get_regularization_loss()
        # Backward pass
        loss.backward()
        
        # Update the weights
        optimizer.step()
        
        # Accumulate the loss
        running_loss += loss.item()
    
    # Print the average loss for the epoch
    epoch_loss = running_loss / (len(train_data) / batch_size)
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}")

# After training, you can save the model
torch.save(model.state_dict(), 'model.pth')
exported_model=model.arch_export()

**Comment by matteorisso** [comment]
Hello @Mojtaba1515, currently PLiNIO supports the usage of batchnorm when placed after a conv or linear layer which is the most common scenario in neural network design. I suppose that the batchnorm layers responsible for the error are self.bn3 and self.bn4. 
Is there a specific reason why you want to have such layers there?

**Comment by Mojtaba1515** [comment]
Dear Matteo
 
Thank you so much for modifying the library. I use bachnorm layer to resolve the problem of gradient vanishing in the backpropagation.

**Comment by matteorisso** [comment]
Hello @Mojtaba1515, that's fine! The problem is that you have two batch-norm layers one after the other, namely bn3 and bn4. The normal set-up, which is the one supported in PLiNIO, is to have the conv-bn-relu or linear-bn-relu sequence! Maybe you can try to remove bn4 (and its subsequent relu) and place bn3 (and its subsequent relu) after fc1.

Best,
Matteo
